### PR TITLE
fix: fix the redirect of the cookie value `PDS_loginToken` (resolves #27)

### LINKED ISSUE #27: Fix the cookie redirect
## Describe the bug
When a user is authenticated by Google, the current login process will redirect back to the referrer URL tracked from the incoming login request. This makes the login token cookie only available to the Personal Data Server domain but not the edge server, so it is impossible to send the login token to the edge proxy API.

## Solution
By looking at [the login workflow](https://github.com/fluid-project/personal-data-server/blob/main/docs/Workflow.md), this redirect should occur in two stages: the edge proxy allocates a special URL space e.g. host/redirect which is directs the PDS/SSO to redirect into, which then has the function of capturing any session token, and then issuing a final, local redirect back to host.

### PR DESCRIPTION
**Pull request by cindyli**
When the google single sign on completes, the personal data server now redirects to the edge proxy API `/api/redirect` with these query parameters: 

* `loginToken`: The login token for future preferences requests
* `maxAge`: The max age of the login token in second
* `refererURL`: The referer URL of the login request. This URL will be used by the Edge Proxy to redirect back to UIO

The edge proxy should then redirect to the `refererURL` with the login token as a cookie value of `PDS_loginToken`.

### CODE REVIEW

**Comment by cindyli** [comment]
@amb26, @klown, this PR has been updated to add: 1. an Edge Proxy example; 2. tests to verify the redirect url issued by the personal data server once the authentication completes.

In terms of tests, what we talked in the June 16 tech meeting is to start the edge proxy to check query parameters received by it. But once the edge proxy /api/redirect receives the redirect call, it immediately redirects to its client side. It's difficult to intercept before the second redirect to check received parameters. [What I did](https://github.com/cindyli/personal-data-server/blob/fix/cookie-redirect/tests/googleSsoTests.js#L242-L248) is to verify the redirect url stored in the response object initiated from the personal data server.

This pull request is ready for more reviews.

File: src/edgeProxy/edgeProxy.js [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+
+const app = require("./app");
+const debug = require("debug")("edgeproxy:server");
+const http = require("http");
+
+/**
+ * Get port from environment and store in Express.
+ */
+
+const port = normalizePort(process.env.EDGEPROXY_PORT || "4000");
```
Comment (amb26) [inline src/edgeProxy/edgeProxy.js:17]: It's not a part of the core infrastructure but this environment variable should probably have the PDS_ prefix like the others for consistency. Also document in the README

**Comment by cindyli** [comment]
@amb26, the review comment has been addressed. Ready for another look. Thanks.

File: src/edgeProxy/package.json [hunk 2]
```diff
@@ -0,0 +1,18 @@
+{
+    "name": "edgeproxy",
+    "version": "0.0.0",
+    "private": true,
+    "scripts": {
+        "buildLib": "rm -rf public/lib; mkdir public/lib; cp -rf node_modules/infusion public/lib/infusion",
```
Comment (amb26) [inline src/edgeProxy/package.json:6]: The ; syntax is only supported on bash and && should be used instead for cross-platform portability

File: src/edgeProxy/views/index.html [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+            </p>
+            <p>How to use:</p>
+            <p>1. Click "Login Personal Data Server Using a Google Account" to login Personal Data Server</p>
+            <p>2. Click "Get Preferences" to retrieve preferences for your account from Personal Data Server</p>
+            <p>3. Click "show preferences" at the top right corner, select your UI preferences. Then click
+                "Save Preferences" to save selected preferences to Personal Data Server
+            </p>
+            <p>4. Click "Logout" to logout Personal Data Server</p>
+
+            <button id="login">Login Personal Data Server Using a Google Account</button>
```
Comment (amb26) [inline src/edgeProxy/views/index.html:63]: Button and text should read "Login to" or "Log in to"

File: src/edgeProxy/README.md [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+**Start Personal Data Server:** run these commands to start Personal Data Server:
+
+```bash
+cd ../..
+npm start
+```
+
+* Open `http://localhost:3000/` in a browser to access Personal Data Server.
+
+Note: Edge Proxy runs on "127.0.0.1" and Personal Data Server runs on "localhost", or vice versa. They should not
```
Comment (amb26) [inline src/edgeProxy/README.md:33]: runs on -> should be run on?

File: src/edgeProxy/README.md [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+both running on the same domain as "127.0.0.1" or "localhost". This is to workaround the issue that the cookie value
```
Comment (amb26) [inline src/edgeProxy/README.md:34]: Should say something like "This will allow for a valid demonstration of transmitting the session cookie value between the different domains that the Personal Data Server and the Edge Proxy would ordinarily be hosted from"

**Comment by cindyli** [comment]
@amb26 all review comments have been addressed. Ready for another round of review. Thanks.

File: src/edgeProxy/package.json [hunk 6]
```diff
@@ -0,0 +1,18 @@
+{
+    "name": "edgeproxy",
+    "version": "0.0.0",
+    "private": true,
+    "scripts": {
+        "buildLib": "rm -rf public/lib; mkdir public/lib && cp -rf node_modules/infusion public/lib/infusion",
+        "start": "npm run buildLib; node edgeProxy.js"
```
Comment (amb26) [inline src/edgeProxy/package.json:7]: This script still contains a non-portable ; operator

Comment (cindyli) [reply src/edgeProxy/package.json]: Good catch, @amb26. It's now addressed.

File: src/edgeProxy/package.json [hunk 7]
```diff
@@ -0,0 +1,18 @@
+{
+    "name": "edgeproxy",
+    "version": "0.0.0",
+    "private": true,
+    "scripts": {
+        "buildLib": "rm -rf public/lib && mkdir public/lib && cp -rf node_modules/infusion public/lib/infusion",
```
[the remark this answers is not in the document]
Comment (cindyli) [reply src/edgeProxy/package.json]: @amb26 thanks for the info about `cpy`. Addressed and ready for another round. Thanks.

File: src/edgeProxy/edgeProxy.js [hunk 8]
```diff
@@ -0,0 +1,92 @@
...
+/**
+ * Event listener for HTTP server "listening" event.
+ */
+
+function onListening() {
+    const addr = server.address();
+    const bind = typeof addr === "string"
+        ? "pipe " + addr
+        : "port " + addr.port;
+    debug("Listening on " + bind);
```
Comment (amb26) [inline src/edgeProxy/edgeProxy.js:91]: Given this is primarily an instructional artefact I think it would be helpful if the listening message was a bit more prominent - by default, debug messages go nowhere. Probably reasonable to log something to the console like 
````
"Personal data server edge proxy listening on port " + addr
````
and perhaps also print to the console the URL which can be used to access the main "Edge Proxy Example" view page

Comment (cindyli) [reply src/edgeProxy/edgeProxy.js]: Good point, @amb26. This has been addressed and ready for another look. Thanks.
